### PR TITLE
shivamkumar's volume controller project final commit

### PR DESCRIPTION
**Pull request by shivamkumar011**

### CODE REVIEW

**Comment by apoorvwankar** [comment]
Everything's good👍👍. Just try renaming the folder to the same format.

**Comment by jhashivam-2001** [comment]
Yup...all good to go now. That GIF in your readme is a quite catchy 💯

**Comment by mridult543** [comment]
All things are good now .

**Comment by heyparitosh** [comment]
> 
> 
> Everything's good👍👍. Just try renaming the folder to the same format.


@shivamkumar011 `VolumeController_KumarShivam`

**Comment by heyparitosh** [comment]
@shivamkumar011 You should add a requirements.txt file.

**Pull request closed without merging**
