### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by apoorvwankar**

### CODE REVIEW

**Comment by jhashivam-2001** [comment]
We had to create a folder with our name and project name inside the "Submission"  folder and the put the files in it. It would also have been nice though to include a working screenshot of the program in the Readme file.

**Comment by shivamkumar011** [comment]
Everything is working fine only adding gif to the readme file is left .

**Comment by jhashivam-2001** [comment]
Perfect enough to be pulled into the main branch. Everything is fine .

**Comment by mridult543** [comment]
Everything is ok now .

**Comment by heyparitosh** [comment]
@apoorvwankar You should add a requirements.txt file.

**Review by heyparitosh — CHANGES_REQUESTED** [review]
Take a look at your requirements.txt file once again. Appears like it has listed all your globally installed packages.

**Review by heyparitosh — APPROVED** [review]
Great work!

**Pull request merged**
