### PR TITLE
files added by Mridul

### PR DESCRIPTION
**Pull request by mridult543**

### CODE REVIEW

**Comment by jhashivam-2001** [comment]
Good Evening ! Please create one more folder within the "Submission" folder with your name and project name and then place all files within it before restarting the PR. Also, it would be a guidance around the submission if you include a README.md file within your newly created folder .

**Comment by apoorvwankar** [comment]
Please add your files in a folder inside the one named "Submission" and rename it with proper format. Also include a README.md file with a proper screenshot/GIF included of the working project. Everything else is good.

**Comment by shivamkumar011** [comment]
Everything else is working nice.Just a readme file is needed  with required information and put your files inside submission folder.

**Comment by heyparitosh** [comment]
@mridult543 Add a requirements.txt file.

**Comment by heyparitosh** [comment]
Project files are missing.

**Comment by heyparitosh** [comment]
@mridult543 
You should rename the folder to the same format as your team members did. 
`VolumeController_MridulTiwari`

**Review by heyparitosh — APPROVED** [review]
Great work!

**Pull request merged**
