### PR TITLE
Shivam Jha's submission for the Volume Controller Project ! 

### PR DESCRIPTION
**Pull request by jhashivam-2001**
With due humbleness this is to request the maintainers to pull my submission for the Gesture Based Volume Controller project in the main branch . 

The readme provides all dependencies to be installed and possible errors that the users can face.

An added advantage of this version is that the user just need to remove the hand from in front of  the webcam and the app terminates itself with no exception thrown !

### CODE REVIEW

**Comment by apoorvwankar** [comment]
Great Work 👍👍. I think everything's up to the mark.

**Comment by shivamkumar011** [comment]
Everything is good ,working nicely.

**Comment by mridult543** [comment]
All things are ok .

**Comment by heyparitosh** [comment]
@jhashivam-2001 Looks great! 
You should add a requirements.txt file and move your `README.md` file within your's project directory `VolumeController_ShivamJha`.

**Pull request closed without merging**
